package:
  name: genesis
  version: "2.4"

source:
  git_url: git@github.com:borismarin/genesis2.4gamma.git
  git_tag: v2.4
  patches:
    - fixbin.patch 
    - rename_convert.patch

build:
  number: 0

test:
  files:
    - test_rng.g
  commands:
    - genesis -nox -batch -notty test_rng.g | grep '0.01426654216 0.7493918538 0.007316101808 0.1527428776 0.1134621128'

about:
  home: http://genesis-sim.org/GENESIS/ 
  license: GPL2
  summary: "GENESIS (short for GEneral NEural SImulation System) is a general purpose simulation platform that was developed to support the simulation of neural systems ranging from subcellular components and biochemical reactions to complex models of single neurons, simulations of large networks, and systems-level models. As such, GENESIS, and its version for parallel and networked computers (PGENESIS) was the first broad scale modeling system in computational biology to encourage modelers to develop and share model features and components."
